### ISSUE TITLE
Migrate to nullsafety

### ISSUE THREAD

**Issue by britannio** [xantiagoma/dart_date#10]
Because dart_date 1.0.9 depends on timeago ^2.0.29 and no versions of dart_date match >1.0.9 <2.0.0, dart_date ^1.0.9 requires timeago ^2.0.29.
So, because *** depends on both timeago ^3.0.0-nullsafety and dart_date ^1.0.9, version solving failed.
pub get failed (1; So, because *** depends on both timeago ^3.0.0-nullsafety and dart_date ^1.0.9, version solving failed.)

**Comment by xantiagoma** [comment]
Hi @britannio 
I've just submitted a pre-release https://pub.dev/packages/dart_date/versions/1.1.0-nullsafety.0 as according to https://dart.dev/null-safety/migration-guide

**Comment by britannio** [comment]
Awesome, thanks for the timely release! 
pub.dev has some feedback though, https://pub.dev/packages/dart_date/versions/1.1.0-nullsafety.0/score
