### ISSUE TITLE
upgrade to flutter 2.0 has error

### ISSUE THREAD

**Issue by joo** [xantiagoma/dart_date#11]
`../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:118:23: Error: The getter 'previousDay' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousDay'.
    return currentDay.previousDay;                                      
                      ^^^^^^^^^^^                                       
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:123:23: Error: The getter 'nextDay' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nextDay'.
    return currentDay.nextDay;                                          
                      ^^^^^^^                                           
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:139:24: Error: The getter 'nextMonth' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nextMonth'.
    return [currentDay.nextMonth.startOfMonth.startOfDay, currentDay.nextMonth.endOfMonth.endOfDay];
                       ^^^^^^^^^                                        
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:139:70: Error: The getter 'nextMonth' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nextMonth'.
    return [currentDay.nextMonth.startOfMonth.startOfDay, currentDay.nextMonth.endOfMonth.endOfDay];
                                                                     ^^^^^^^^^
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:145:18: Error: The getter 'nextWeek' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nextWeek'.
      currentDay.nextWeek.startOfISOWeek.startOfDay,                    
                 ^^^^^^^^                                               
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:146:18: Error: The getter 'nextWeek' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nextWeek'.
      currentDay.nextWeek.endOfISOWeek.endOfDay                         
                 ^^^^^^^^                                               
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:152:24: Error: The getter 'startOfISOWeek' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startOfISOWeek'.
    return [currentDay.startOfISOWeek.startOfDay, currentDay.endOfISOWeek.endOfDay];
                       ^^^^^^^^^^^^^^                                   
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:152:62: Error: The getter 'endOfISOWeek' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'endOfISOWeek'.
    return [currentDay.startOfISOWeek.startOfDay, currentDay.endOfISOWeek.endOfDay];
                                                             ^^^^^^^^^^^^
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:158:18: Error: The getter 'previousWeek' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousWeek'.
      currentDay.previousWeek.startOfISOWeek.startOfDay,                
                 ^^^^^^^^^^^^                                           
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:159:18: Error: The getter 'previousWeek' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousWeek'.
      currentDay.previousWeek.endOfISOWeek.endOfDay                     
                 ^^^^^^^^^^^^                                           
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:165:24: Error: The getter 'startOfMonth' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startOfMonth'.
    return [currentDay.startOfMonth.startOfDay, currentDay.endOfMonth.endOfDay];
                       ^^^^^^^^^^^^                                     
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:165:60: Error: The getter 'endOfMonth' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'endOfMonth'.
    return [currentDay.startOfMonth.startOfDay, currentDay.endOfMonth.endOfDay];
                                                           ^^^^^^^^^^   
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:171:18: Error: The getter 'previousMonth' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousMonth'.
      currentDay.previousMonth.startOfMonth.startOfDay,                 
                 ^^^^^^^^^^^^^                                          
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:172:18: Error: The getter 'previousMonth' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousMonth'.
      currentDay.previousMonth.endOfMonth.endOfDay                      
                 ^^^^^^^^^^^^^                                          
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:183:54: Error: The method 'addDays' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing method, or defining a method named 'addDays'.
    var endCurrentQuarter = DateTime(year, month, 1).addDays(-1);       
                                                     ^^^^^^^            
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:184:33: Error: The getter 'startOfDay' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startOfDay'.
    return [startCurrentQuarter.startOfDay, endCurrentQuarter.endOfDay];
                                ^^^^^^^^^^                              
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:189:41: Error: The method 'addDays' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing method, or defining a method named 'addDays'.
    var endPreviousQuarter = quarter[0].addDays(-1);                    
                                        ^^^^^^^                         
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:191:34: Error: The getter 'startOfDay' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startOfDay'.
    return [startPreviousQuarter.startOfDay, endPreviousQuarter.endOfDay];
                                 ^^^^^^^^^^                             
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:196:24: Error: The getter 'startOfYear' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'startOfYear'.
    return [currentDay.startOfYear.startOfDay, currentDay.endOfYear.endOfDay];
                       ^^^^^^^^^^^                                      
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:196:59: Error: The getter 'endOfYear' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'endOfYear'.
    return [currentDay.startOfYear.startOfDay, currentDay.endOfYear.endOfDay];
                                                          ^^^^^^^^^     
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:202:18: Error: The getter 'previousYear' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousYear'.
      currentDay.previousYear.startOfYear.startOfDay,                   
                 ^^^^^^^^^^^^                                           
../../smart_dart_lib/smart_dart/lib/src/smart_base.dart:203:18: Error: The getter 'previousYear' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field named 'previousYear'.
      currentDay.previousYear.endOfYear.endOfDay                        
                 ^^^^^^^^^^^^                                           
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/joo/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/home/joo/opt/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org     `

**Comment by joo** [comment]
Before upgrade, flutter 1.22, that's ok.

**Comment by joo** [comment]
`ERR : Because dart_date >=1.0.1 <1.1.0-nullsafety.0 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0, dart_date >=1.0.1 <1.1.0-nullsafety.0 is incompatible with flutter_localizations from sdk.
    | So, because kingbar_for_cloud_client depends on both flutter_localizations any from sdk and dart_date 1.0.9, version solving failed.`

**Comment by allanwolski** [comment]
@xantiagoma, can you see that?

**Comment by xantiagoma** [comment]
@joo  Can you check with `1.1.0`?
