### ISSUE TITLE
Incorrect isWeekend outputs 

### ISSUE THREAD

**Issue by logiczsniper** [xantiagoma/dart_date#19]
![image](https://user-images.githubusercontent.com/31292294/151707717-b370e5e1-f6f5-4531-af6d-3aad69068bb7.png)

Based on the source code (below), it makes sense why this is happening. `DateTime.saturday` and `DateTime.sunday` are just `6` and `7` respectively (see `DateTime` source below).
```dart
day == DateTime.saturday || day == DateTime.sunday;
```

![image](https://user-images.githubusercontent.com/31292294/151707794-eb225a3a-e769-4a1e-bcbe-3ad95a40fd04.png)

I can fix this if you'd like.

**Comment by avbk** [comment]
Workaround for now: 
```dart
extension on DateTime {
  /// Return true if this [DateTime] is a saturday or a sunday
  bool get isWeekendFixed =>
      weekday == DateTime.saturday || weekday == DateTime.sunday;
}
```

**Comment by xantiagoma** [comment]
Change applied on version [1.3.2](https://pub.dev/packages/dart_date/versions/1.3.2)
