### ISSUE TITLE
Intl upgrade

### ISSUE THREAD

**Issue by CrisNegoianu** [xantiagoma/dart_date#26]
Hi.

Please upgrade the intl dependency to 0.18.0.

Thank you for your hard work.

**Comment by baneeishaque** [comment]
Use this fork : https://github.com/spaznuski/dart_date

**Comment by CrisNegoianu** [comment]
Thank you.

**Comment by angus-clark** [comment]
> Use this fork : https://github.com/spaznuski/dart_date

How do I use the fork in a flutter project?

**Comment by ArinFaraj** [comment]
> How do I use the fork in a flutter project?

```  
some_package:
  git:
    url: https://github.com/User/somepackage.git
```

**Comment by TatsuUkraine** [comment]
hi, any update on this?
