### ISSUE TITLE
isXXXday always false

### ISSUE THREAD

**Issue by ghost** [xantiagoma/dart_date#3]
Hey, the following unit test is valid. It seems that all weekday properties are false, so no branches of the if-else construct are used. I am running on Flutter 1.22.0 and the plugin version is 1.0.7.

`test("my test", () {
    if (DateTime.now().isMonday) {
      print("monday");
      expect(false, isTrue);
    } else if (DateTime.now().isTuesday) {
      print("tuesday");
      expect(false, isTrue);
    } else if (DateTime.now().isWednesday) {
      print("wednesday");
      expect(false, isTrue);
    } else if (DateTime.now().isThursday) {
      print("thursday");
      expect(false, isTrue);
    } else if (DateTime.now().isFriday) {
      print("friday");
      expect(false, isTrue);
    } else if (DateTime.now().isSaturday) {
      print("saturday");
      expect(false, isTrue);
    } else if (DateTime.now().isSunday) {
      print("sunday");
      expect(false, isTrue);
    }
    expect(false, isFalse);
  });`

**Comment by xantiagoma** [comment]
Hi @xmashallax Issue should be solved on version 1.0.8

Thank you for your input 😄
