### ISSUE TITLE
Rename Date extension

### ISSUE THREAD

**Issue by tjarvstrand** [xantiagoma/dart_date#38]
Hi!

Thanks for a great library!

I have a `Date` class of my own which represents a date without a time, and it gets really messy when I want to use both that and dart_date from the same file. I was wondering if you'd be open to changing the name of the `Date` extension class?

I'd also be happy to submit my `Date` implementation as a contribution to dart_date, if there's interest?

**Comment by xantiagoma** [comment]
Included in #40

**Comment by tjarvstrand** [comment]
Awesome, thanks!
