### ISSUE TITLE
Modifying month does not consider number of days in months

### ISSUE THREAD

**Issue by Feenposhleen** [xantiagoma/dart_date#9]
Found an oddity that caused a bug in my app:

```
final date = DateTime('2021-01-29');
date.addMonth(1);
print(date.month);
// 3
```

If it's too much work to fix it by setting date to closest possible one, it should atleast be mentioned in the doc. 
Thanks!

**Comment by xantiagoma** [comment]
Hi @Feenposhleen 
You're right, as `month` per historical reasons is not a fixed time value is a complicated topic.

the library it's using the default `DateTime` behaviour 
![image](https://user-images.githubusercontent.com/1217807/107303014-3f7ac000-6a4c-11eb-8d3e-cddaf6dca09c.png)

I tried some workarounds but not all of them worked, as you see in the example it returns the immediate ending of the month/begging of next month at 0:00 hours.

I don't know your specific use case but you can implement a custom logic like if day > 28 and the returned date is the same as the `startOfMonth` subtract a second or similar.

I hope I have been helpful, any PR is welcome.
